const LOGGING_IN= "LOGGING_IN";
const LOG_IN_ERROR= "LOG_IN_ERROR";
const LOG_IN_SUCCESS= "LOG_IN_SUCCESS";

const SIGNING_UP= "SIGNING_UP";
const SIGN_UP_ERROR= "SIGN_UP_ERROR";
const SIGN_UP_SUCCESS= "SIGN_UP_SUCCESS";

const DISEASES_POST_SUCCESS="DISEASES_POST_SUCCESS";
const DISEASES_POST_FAIL="DISEASES_POST_FAIL";
const DISEASES_POST_LOADING="DISEASES_POST_LOADING";

const DISEASES_FETCH_SUCCESS="DISEASES_FETCH_SUCCESS";
const DISEASES_FETCH_FAIL="DISEASES_FETCH_FAIL";
const DISEASES_FETCH_LOADING="DISEASES_FETCH_LOADING";

const GET_DISEASE_SUCCESS="GET_DISEASE_SUCCESS";
const GET_DISEASE_FAIL="GET_DISEASE_FAIL";
const GET_DISEASE_LOADING="GET_DISEASE_LOADING";

const DELETE_DISEASE_SUCCESS="DELETE_DISEASE_SUCCESS";
const DELETE_DISEASE_FAIL="DELETE_DISEASE_FAIL";
const DELETE_DISEASE_LOADING="DELETE_DISEASE_LOADING";

const types={
    login: {
        LOGGING_IN,
        LOG_IN_ERROR,
        LOG_IN_SUCCESS
    },
    sign_up:{
        SIGNING_UP,
        SIGN_UP_ERROR,
        SIGN_UP_SUCCESS
    },
    diseases:{
        DISEASES_POST_SUCCESS,
        DISEASES_POST_FAIL,
        DISEASES_POST_LOADING,
        DISEASES_FETCH_LOADING,
        DISEASES_FETCH_FAIL,
        DISEASES_FETCH_SUCCESS
    },
    disease:{
        GET_DISEASE_SUCCESS,
        GET_DISEASE_FAIL,
        GET_DISEASE_LOADING,
        DELETE_DISEASE_FAIL,
        DELETE_DISEASE_LOADING,
        DELETE_DISEASE_SUCCESS
    }
};

export default types;
